language: php
sudo: false

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --no-ansi --dev

script:
  - vendor/bin/codecept --version
  - vendor/bin/codecept run --coverage-xml
  - vendor/bin/php-cs-fixer fix --version
  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no

after_success:
  - bash <(curl -s https://codecov.io/bash)